UniversityDapperDemo/UniversityDapper/Models/ErrorViewModel.cs
namespace UniversityDapper.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UniversityDapperDemo/UniversityDapper/Models/Faculty.cs
namespace UniversityDapper.Models
{
    public class Faculty
    {
        public int Id { get; set; }

        public string? FacultyName { get; set; }

        public int UniversityId { get; set; }

        public University? University { get; set; }
    }
}

UniversityDapperDemo/UniversityDapper/Models/University.cs
namespace UniversityDapper.Models
{
    public class University
    {
        public int Id { get; set; }

        public string UniversityName { get; set; }

        public string Phone {  get; set; }
    }
}

UniversityDapperDemo/UniversityDapper/Controllers/FacultyController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using UniversityDapper.Models;
using UniversityDapper.Repositories.Faculties;

namespace UniversityDapper.Controllers
{
    public class FacultyController : Controller
    {
        private readonly IFacultyRepository _facultyRepository;

        private SelectList _universitiesList;

        public FacultyController(IFacultyRepository facultyRepository)
        {
            _facultyRepository = facultyRepository;
            _universitiesList = new SelectList(
                    _facultyRepository.GetAllUniversities(),
                    nameof(University.Id),
                    nameof(University.UniversityName)
                 );
        }

        public ActionResult Index()
        {
            return View(_facultyRepository.GetAll());
        }

        

        // GET: FacultyController/Create
        public ActionResult Create()
        {
            ViewBag.Universities = _universitiesList;

            return View();
        }

        // POST: FacultyController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Faculty faculty)
        {
            try
            {
                _facultyRepository.Add(faculty);

                TempData["message"] = "Datos guardados exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;
                ViewBag.Universities = _universitiesList;

                return View(faculty);
            }
        }

        // GET: FacultyController/Edit/5
        public ActionResult Edit(int id)
        {
            var faculty = _facultyRepository.GetById(id);
            ViewBag.Universities = _universitiesList;

            if (faculty == null)
            {
                return NotFound();
            }

            return View(faculty);
        }

        // POST: FacultyController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Faculty faculty)
        {
            try
            {
                _facultyRepository.Edit(faculty);

                TempData["message"] = "Datos editados correctamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Universities = _universitiesList;
                return View(faculty);
            }
        }

        // GET: FacultyController/Delete/5
        public ActionResult Delete(int id)
        {
            var faculty = _facultyRepository.GetById(id);

            if (faculty == null)
            {
                return NotFound();
            }

            return View(faculty);
        }

        // POST: FacultyController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Faculty faculty)
        {
            try
            {
                _facultyRepository.Delete(faculty.Id);

                TempData["message"] = "Dato eliminado exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(faculty);
            }
        }
    }
}

UniversityDapperDemo/UniversityDapper/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using UniversityDapper.Models;

namespace UniversityDapper.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

UniversityDapperDemo/UniversityDapper/Controllers/UniversityController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using UniversityDapper.Models;
using UniversityDapper.Repositories.Universities;

namespace UniversityDapper.Controllers
{
    public class UniversityController : Controller
    {
        private readonly IUniversityRepository _universityRepository;

        public UniversityController(IUniversityRepository universityRepository)
        {
            _universityRepository = universityRepository;
        }

        public ActionResult Index()
        {
            return View(_universityRepository.GetAll());
        }

        // GET: UniverstiyController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UniverstiyController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UniverstiyController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(University university)
        {
            try
            {
                _universityRepository.Add(university);

                TempData["message"] = "Datos guardados exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                TempData["message"] = ex.Message;

                return View(university);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var university = _universityRepository.GetById(id);

            if(university == null)
            {
                return NotFound();
            }

            return View(university);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(University university)
        {
            try
            {
                _universityRepository.Edit(university);

                TempData["message"] = "Datos editados correctamente";

                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                return View(university);
            }
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var university = _universityRepository.GetById(id);

            if(university == null)
            {
                return NotFound();
            }

            return View(university);
        }

        // POST: UniverstiyController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(University university)
        {
            try
            {
                _universityRepository.Delete(university.Id);

                TempData["message"] = "Dato eliminado exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                return View(university);
            }
        }
    }
}

UniversityDapperDemo/UniversityDapper/Views/Faculty/Create.cshtml
@model UniversityDapper.Models.Faculty

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Faculty</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="FacultyName" class="control-label"></label>
                <input asp-for="FacultyName" class="form-control" />
                <span asp-validation-for="FacultyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UniversityId" class="control-label"></label>
                <select class="form-select" asp-for="UniversityId" asp-items="@ViewBag.Universities" id="universitySearch">
                    <option value="">Seleccione una Universidad</option>
                </select>
                <span asp-validation-for="UniversityId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-success mt-2" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-primary mt-2">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $('#universitySearch').select2({
            language: "es",
            width: '100%',
            placeholder: "Seleccione una Universidad",
        });

    </script>
}

UniversityDapperDemo/UniversityDapper/Views/Faculty/Delete.cshtml
@model UniversityDapper.Models.Faculty

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Faculty</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FacultyName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FacultyName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UniversityId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UniversityId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Eliminar" class="btn btn-danger mt-2" /> |
        <a asp-action="Index" class="btn btn-primary mt-2">Back to List</a>
    </form>
</div>

UniversityDapperDemo/UniversityDapper/Views/Faculty/Edit.cshtml
@model UniversityDapper.Models.Faculty

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Faculty</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FacultyName" class="control-label"></label>
                <input asp-for="FacultyName" class="form-control" />
                <span asp-validation-for="FacultyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UniversityId" class="control-label"></label>
                <select class="form-select" asp-for="UniversityId" asp-items="@ViewBag.Universities" id="universitySearch">
                    <option value="">Seleccione una Universidad</option>
                </select>
                <span asp-validation-for="UniversityId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Editar" class="btn btn-warning mt-2" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-primary mt-2">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $('#universitySearch').select2({
            language: "es",
            width: '100%',
            placeholder: "Seleccione una Universidad",
        });

    </script>
}

UniversityDapperDemo/UniversityDapper/Views/Faculty/Index.cshtml
@model IEnumerable<UniversityDapper.Models.Faculty>

@{
    ViewData["Title"] = "Index";
}

<h1 class="mb-3">Facultades</h1>

<p>
    <a asp-action="Create" class="btn btn-success">Nueva Facultad</a>
</p>

@if (TempData["message"] != null)
{
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
        @TempData["message"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<table class="table table-bordered table-striped table-responsive mt-2">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                Facultad
            </th>
            <th>
                Universidad
            </th>
            <th>
                Acciones
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FacultyName)
            </td>
            <td>
                @item.University?.UniversityName
            </td>
                <td>
                    <a asp-controller="Faculty"
                       asp-action="Edit"
                       asp-route-id="@item.Id"
                       class="btn btn-warning">
                        Editar
                    </a>
                    <a asp-controller="Faculty"
                       asp-action="Delete"
                       asp-route-id="@item.Id"
                       class="btn btn-danger">
                        Eliminar
                    </a>
                </td>
        </tr>
}
    </tbody>
</table>

UniversityDapperDemo/UniversityDapper/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

UniversityDapperDemo/UniversityDapper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UniversityDapper</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UniversityDapper.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UniversityDapper</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="University" asp-action="Index">
                                Universidades
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Faculty" asp-action="Index">
                                Facultades
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - UniversityDapper - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/i18n/es.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UniversityDapperDemo/UniversityDapper/Views/University/Create.cshtml
@model UniversityDapper.Models.University

@{
    ViewData["Title"] = "Create";
}

<h1>Nueva Universidad</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="UniversityName" class="control-label"></label>
                <input asp-for="UniversityName" class="form-control" />
                <span asp-validation-for="UniversityName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-primary mt-2">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

UniversityDapperDemo/UniversityDapper/Views/University/Delete.cshtml
@model UniversityDapper.Models.University

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>University</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UniversityName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UniversityName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Eliminar" class="btn btn-danger mt-2" /> |
        <a asp-action="Index" class="btn btn-primary mt-2">Back to List</a>
    </form>
</div>

UniversityDapperDemo/UniversityDapper/Views/University/Edit.cshtml
@model UniversityDapper.Models.University

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar Universidad</h1>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UniversityName" class="control-label"></label>
                <input asp-for="UniversityName" class="form-control" />
                <span asp-validation-for="UniversityName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Editar" class="btn btn-warning" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-primary mt-2">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

UniversityDapperDemo/UniversityDapper/Views/University/Index.cshtml
@model IEnumerable<UniversityDapper.Models.University>

@{
    ViewData["Title"] = "Index";
}

<h1 class="mb-3">Universidades</h1>

<p>
    <a asp-action="Create" class="btn btn-success">Nueva universidad</a>
</p>

@if(TempData["message"] != null)
{
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
        @TempData["message"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<table class="table table-bordered table-striped table-responsive mt-2">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UniversityName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                Acciones
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UniversityName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                <a 
                    asp-controller="University" 
                    asp-action="Edit" 
                    asp-route-id="@item.Id"
                    class="btn btn-warning"
                >Editar
                </a>
                <a 
                    asp-controller="University" 
                    asp-action="Delete" 
                    asp-route-id="@item.Id"
                    class="btn btn-danger"
                >Eliminar
                </a>
            </td>
        </tr>
}
    </tbody>
</table>